# This is a basic workflow to help you get started with Actions

name: Cookbooks Upload

on: [ push, workflow_dispatch ]
  
jobs:
  Kitchen-Test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Check if Chef installed
        continue-on-error: true
        id: check
        run: chef -v
        
      - name: Install ChefWorkstation v21.2.278
        if: steps.check.outcome == 'failure'
        run: |
          wget https://packages.chef.io/files/stable/chef-workstation/21.2.278/el/8/chef-workstation-21.2.278-1.el7.x86_64.rpm
          sudo rpm -ivh chef-workstation-21.2.278-1.el7.x86_64.rpm
          chef -v
  
      - name: Install Docker
        run: |
          sudo yum update -y
          sudo yum install -y yum-utils device-mapper-persistent-data lvm2
          sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          sudo yum install -y docker-ce docker-ce-cli containerd.io
          docker -v
          sudo usermod -aG docker $USER
          sudo chmod 666 /run/docker.sock
          sudo service docker start
          service docker status

      - name: Converge
        run: |
          kitchen destroy
          kitchen create
          kitchen converge
          
      - name: Test
        run: kitchen verify
        
      - name: Cleanup Containers 
        if: always()
        run: kitchen destroy

  Cookbook-Upload:
    runs-on: self-hosted
    needs: Kitchen-Test
    steps:
      - name: Uploading Cookbooks to Chef Server
        run: |
          rm Berksfile.lock
          berks install
          berks upload --force
